spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    logging.level.org.flywaydb: DEBUG
    logging.level.org.springframework.boot.autoconfigure.flyway: DEBUG

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24 hours

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method


logging:
  level:
    com.example: DEBUG